### ISSUE TITLE
Authorization header does not set when auth is optional

### ISSUE THREAD

**Issue by channprj** [scalar/scalar#1939]
### What happens?

![image](https://github.com/scalar/scalar/assets/1831308/76f29869-1f5e-48fa-922a-2b08b283b40a)

`Authorization` header doesn't set in CDN mode.

I think it's related with `$ref` issue.

![image](https://github.com/scalar/scalar/assets/1831308/524334e6-c197-4c81-8001-8ba1444fed9b)

### What did you expect to happen?

![image](https://github.com/scalar/scalar/assets/1831308/e0f04228-3667-4f6f-b568-8bff065591e9)

### How can we reproduce the issue?

1. Deploy with CDN
2. Send request
3. Authorization does not set

### OpenAPI Document

https://sandbox.scalar.com/e/G8yz4

**Comment by hanspagel** [comment]
Thanks for the report! I don’t have the chance to check it right now, but my gut tells me it’s not related to the parser error.

**Comment by hanspagel** [comment]
Finally got time to look at this! Thanks for the report. 

This is happening because the API defintion has an empty object `{}` in the `security` array:

```diff
"security": [
  {
    "cookieAuth": []
  },
  {
    "basicAuth": []
  },
+  {}
],
```

According to the OpenAPI 3.0.3 specification, this makes authentication optional:

> To make security optional, an empty security requirement ({}) can be included in the array. 
>
> Source: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#operation-object

And if no authentication is required, we don't add it to the example request. Personally, I think that’s fine. What do you think @marclave? 

Here is a sandbox without the empty object:
https://sandbox.scalar.com/e/lIISF

**Comment by channprj** [comment]
@hanspagel Thank you for your analysis. I intended authentication to be optional in that case. Please consider adding an authentication header. I wish that it could be added by entering the authentication header value.

### Reference

- https://github.com/tfranzel/drf-spectacular/issues/99#issuecomment-781243568

**Comment by marclave** [comment]
yeah i think thats good @hanspagel ! :)
