### ISSUE TITLE
ASP.NET 8 - Can't render complex types

### ISSUE THREAD

**Issue by carloscds** [scalar/scalar#1994]
### What happens?

Using this code in C#:

[HttpGet("Cast")]
public IActionResult GetCast()
{
    var summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };
    var forecast = Enumerable.Range(1, 5).Select(index =>
            new WeatherForecast
            (
                DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                Random.Shared.Next(-20, 55),
                summaries[Random.Shared.Next(summaries.Length)]
            ))
            .ToList();
    return Ok(forecast);
}

Or same code in Minimal API:

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})

Scalar can't render response:
![image](https://github.com/scalar/scalar/assets/1697221/a0210607-ab0a-4e16-9986-3b5fbcebece6)

### What did you expect to happen?

Render like Swagger:
[{"Date":"2024-06-08","TemperatureC":25,"Summary":"Balmy","TemperatureF":76},{"Date":"2024-06-09","TemperatureC":4,"Summary":"Warm","TemperatureF":39},{"Date":"2024-06-10","TemperatureC":41,"Summary":"Freezing","TemperatureF":105},{"Date":"2024-06-11","TemperatureC":26,"Summary":"Sweltering","TemperatureF":78},{"Date":"2024-06-12","TemperatureC":-1,"Summary":"Bracing","TemperatureF":31}]

### How can we reproduce the issue?

Create a sample app using minimal API and default template. Add Scalar and run.

**Comment by djesusnet** [comment]
It seems I am experiencing the same issue reported previously when using Scalar to render responses from minimal APIs in C#. 

Scalar cannot render the response and instead shows an error image.

**Expected Behavior:**
I expected the response to render as a JSON array, similar to how Swagger displays it.

**Steps to Reproduce:**
1. Create a sample app using the minimal API template.
2. Add Scalar.
3. Run the application.

I am encountering the same problem as reported.
