### ISSUE TITLE
When executed `yarn` in directory `examples/docusaurus`, got error: "Usage Error: This project is configured to use pnpm" 

### ISSUE THREAD

**Issue by bluishoul** [scalar/scalar#2395]
### What happens?

I followed the instruction in example here: https://github.com/scalar/scalar/tree/main/examples/docusaurus

When executed `yarn` in directory `examples/docusaurus`, I got error like:
```
╭─~/Projects/src/github.com/scalar/scalar/examples/docusaurus ‹main›
╰─$ yarn
Usage Error: This project is configured to use pnpm

$ yarn ...
```

### What did you expect to happen?

`yarn install` works correctly

### How can we reproduce the issue?

1. Clone the repo
2. Go to directory `examples/docusaurus`
3. Run `yarn`

**Comment by hanspagel** [comment]
Unfortunately, we require `pnpm`. It just works slightly different in monorepo (multiple projects in one repository).

Also, yarn is known for compatibility issues. Until last year I was using yarn, too. But I switched to pnpm and never looked back. I’ve had way fewer issues and I think it’s even faster. If you already have Node on your machine, you only need to run `corepack enable` to enable pnpm. You should give it a try! It’s as easy as:

```bash
corepack enable
pnpm install
```

Anyway, for the issue here: We don’t plan to migrate to yarn and we can’t really support both in parallel. That said, the actual docusaurus integration should be installable with yarn. :)

**Comment by tkalejaiye** [comment]
Hey, having this same issue but a little confused by your reply @hanspagel. I ran the commands you shared, then attempted to run the docusaurus example using the instructions in the readme but it still doesn't work
![Screenshot 2024-09-01 at 21 17 08](https://github.com/user-attachments/assets/7c33e0a7-4a90-4d7b-9b50-aff0b1b15340)
