### ISSUE TITLE
[DOC-1210] Think of UX for inserting examples into the API Client

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#269]
For instance, all parameters & bodies can have examples and we should have the ability to showcase the examples and also easily import them to use for a request

<sub>[DOC-1210](https://linear.app/api-docs/issue/DOC-1210/think-of-ux-for-inserting-examples-into-the-api-client)</sub>

**Comment by shfrmn** [comment]
@marclave That would be a big improvement. Is it in principle any different from inserting default values? Currently the app already substitutes defaults, so seems like it's just a matter of picking one of the example values when default is not provided?

**Comment by shfrmn** [comment]
@marclave I did a quick search in the codebase and seems like the reason example substitution doesn't work consistently is because sometimes the property is called `.example` and contains a single value ([working scenario](https://github.com/scalar/scalar/blob/9c880d04c557cbe011cfecdd6fb2a602704bcb2f/packages/api-reference/src/helpers/getExampleFromSchema.ts#L26)) and sometimes it's called `.examples` and contains an array of values (not supported).

The output definitely depends on the tooling a lot. I'm using `fastify-swagger` plugin for generating the spec, and it's very inconsistent. Even with a single example value it will use `.example` for query params, but `.examples` array for request body. Moreover, adding multiple examples for a query param results in the following format, which is unfortunately also [compliant with the spec](https://swagger.io/specification/#example-object)
```
"examples": {
   "2a1cd0f4-69d3-4fc1-8958-ddf40a8e3fc1": {
     "value": "2a1cd0f4-69d3-4fc1-8958-ddf40a8e3fc1"
    }
}
```

**Comment by shfrmn** [comment]
Update: I researched the issue more and discovered two things:
- Only `.example` field is valid within schema objects and their properties
- `.examples` containing an array is a bug in fastify swagger plugin

I submitted a PR to `fastify-swagger` that will fix both issues. 

Multiple `.examples` in the object form are still allowed at the top level of `content` and `response` objects, so those should probably be supported by the UI, but it's a pretty minor issue.

**Comment by hanspagel** [comment]
I think we support both now. :) If you still have issues with that, feel free to reopen. ✌️
