### ISSUE TITLE
secuirty param using securitySchemes in path does not show up in UI

### ISSUE THREAD

**Issue by rajnandan1** [scalar/scalar#293]
### Expected Behavior

In the openapi spec (3.0.0), the path has `security` object it does not show up in the UI. 

### Actual Behavior

Path level security headers should be shown like is redocly or swagger editor 
<img width="927" alt="Screenshot 2023-10-18 at 12 21 46 PM" src="https://github.com/scalar/scalar/assets/16224367/1d79feb4-b381-4d0f-b6f3-bea2c5a6600a">

### Reproduction steps

1. Go to https://www.frogment.com/edit/raj-debug/cashfree-oct18.json#paths/_orders.yaml
2. Click on Preview
3. Open a new tab an go to https://www.frogment.com/edit/raj-debug/cashfree-oct18.json#components/securitySchemes/XClientID.yaml

### Version

CDN

### What browsers are you seeing the problem on?

Firefox

**Comment by marclave** [comment]
@rajnandan1 the wonderful @hanspagel is working on securitySchemas in https://github.com/scalar/scalar/pull/311

Since we are going to be adding the auth at the root level to pass down to all endpoints + the ability to do auth in each endpoint, I think that would solve this.

@hanspagel what do you think?

**Comment by marclave** [comment]
Yeah so I think #311 will solve this, let's see where we get with it and then can get a good feel for this being resolved :)
