### ISSUE TITLE
Set the URL to the active sidebar item

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#296]
Currently, the IntersectionObserver sets the URL. The URL is then set to the section that’s becoming visible, not to the active item (which is the first item in the sidebar, where the section visible).

**Comment by Mohib834** [comment]
@hanspagel  Please assign it to me, I'll pick this up.

**Comment by marclave** [comment]
Done @Mohib834 , thanks for wanting to tackle this ✨

**Comment by Mohib834** [comment]
I am able to pinpoint the issue but couldn't figure out the full solution yet. 

basically, it is happening because the intersection observer is getting triggered as soon as the next section enters the view triggering the active state of the next element on the sidebar and removing it from the current one. 

I am able to adjust the threshold depending on the height of each section. So this is somewhat fixed.

```vue
onMounted(async () => {
  // Setting different threshold depending on the height of element.
  await nextTick()
  const _threshold =
    (intersectionObserverRef.value?.offsetHeight ?? 0) >= window.innerHeight
      ? 0.3
      : 0.8

  useIntersectionObserver(
    intersectionObserverRef,
    ([{ isIntersecting }]) => {
      if (!props.id) {
        return
      }

      setSidebarIdVisibility(props.id, isIntersecting)

      if (isIntersecting) {
        emit('intersecting')
        const newUrl = `${window.location.origin}${window.location.pathname}#${props.id}`
        window.history.replaceState({}, '', newUrl)
      }
    },
    {
      rootMargin: `0px 0px -20% 0px`,
      threshold: _threshold,
    },
  )
})
```

But things breaks when there are two visible sections with very small height comes into the view, when this happens the intersection observer first trigger for the first section and then for the other modifiying the state of active sidebar element and also modifying the url.

Would love to have some help on this please @hanspagel @marclave

**Comment by hanspagel** [comment]
Good find! I’m about to do a bigger refactoring and introduce a `useNavigation` composable and I think this would solve the issue, too. Would you mind if I take from here?

**Comment by Mohib834** [comment]
> Good find! I’m about to do a bigger refactoring and introduce a `useNavigation` composable and I think this would solve the issue, too. Would you mind if I take it from here?

Sure, Thanks.
