### ISSUE TITLE
Make the use of window.location as the base url an option

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#301]
We’re using the current url (window.location) as a fallback for the server URL. There’s only one use case, where that’s helpful: When rendering the reference through the fastify plugin.

We should only use that as the fallback for the fastify plugin and need to make it a config option.

**Comment by mrchimp** [comment]
It would be helpful to be able to override this so that we could define the server url as a relative path and then allow define the domain to run commands against as something other than the domain that the docs are being hosted under.

E.g. the server url could be set to `/api`, the remote request URL (or whatever you want to call it) could be `https://example.com` and requests would be made to `https://example.com/api`.

**Comment by hanspagel** [comment]
You can just add https://example.com/api as a server URL then, that should work just fine! I’m closing this issue, because I think the way to go here is to add whatever users want to their OpenAPI file.
