### ISSUE TITLE
Investigate bundle size on type imports with Bun [DOC-1435]

### ISSUE THREAD

**Issue by marclave** [scalar/scalar#744]
### Expected Behavior

when I did the ElysiaJS integration, I imported the types but didn't notice the build size almost doubled.

```
import type { ReferenceConfiguration } from '@scalar/api-reference'
```

I wonder if there's a way to reduce the bundle size with tree shaking for bun so this doesnt happen in the future, it would be really nice to import the types so we can make a change in our repo and it updates across all our integrations.

https://github.com/elysiajs/elysia-swagger/commit/d9bf105644dd081bdd4819812f51505d831bca85#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410a

### Actual Behavior

https://twitter.com/JamesMoger/status/1744069757924413915

### Reproduction steps

```bash
install latest scalar in a bun project
import only the types
do a build
build size is doubled with lots of packages
```

### Version

latest

<sub>[DOC-1435](https://linear.app/api-docs/issue/DOC-1435/investigate-bundle-size-on-type-imports)</sub>

**Comment by hanspagel** [comment]
Are you saying there is a difference between NodeJS and bun in that regard?

**Comment by jaens** [comment]
Sounds like a problem with bun? Other bundlers definitely do not include `type`-only imports...

**Comment by hanspagel** [comment]
Maybe related
https://twitter.com/gregberge_/status/1760341181396111843

**Comment by hanspagel** [comment]
TIL barrel files are bad
https://dev.to/thepassle/barrel-files-a-case-study-o5p

**Comment by amritk** [comment]
What I thought barrels are recommended? What are you doing to me hanssssss. Good article though something we can definitely improve on 👍🏾. I always thought the bundler would treeshake out everything you don't use. Something to think about for sure.

Yea I think this is on the import side not on the references side, though we could reduce our package use at some point.

Also I did not know about that you HAVE to `import type {}` I will add that eslint rule 🖖🏾  

We should setup some tests to see whats going on

**Comment by jaens** [comment]
@amritk It's useful to actually read the article :upside_down_face: 

> For our __local development environment__, and also for running our unit tests, we don't bundle; we use __buildless__ development, and we get a lot of benefits from this approach.

---

>  always thought the bundler would treeshake out everything you don't use.

Yes. That is what happens. In production.

In development, eg. Vite does something slightly different: It does not treeshake, but it pre-bundles external dependencies into *one* file.  
This still causes absolutely all JS code to be loaded when using barrel files, but since it's one file and browsers can just *parse* (but not necessarily execute) hundreds of megabytes of JS per second (on dev machines), it's not a huge issue.

The author seems to be using the most barebone development environment possible, which yeah, does not work well with hundred-module barrel graphs.

Though as a solution, I would rather suggest the author should start using tools actually meant for large production-grade software. The barrel file ship has already sailed.

**Comment by hanspagel** [comment]
Yeah, that’s what I thought, too. Tree-shaking is hard though and I’ve had too many cases where tree shaking didn’t work as expected, so definitely something worth to keep an eye on.

That said, before replacing any barrel files we should have a proof that we’re actually improving something. 😅

**Comment by amritk** [comment]
haha no no I don't think barrels are going anywhere. Just that import type thing so the whole module doesn't get imported when you just want types doesn't hurt 😄

**Comment by amritk** [comment]
SO basically we just need to fix treeshaking and this should be good
